"""Input resolution and overwrite-safety for ``gitops-scaffold generate``.

Kept out of ``cli.py`` so the CLI stays a thin orchestration layer (see
``docs/architecture.md``).
"""

from __future__ import annotations

import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path

from pydantic import ValidationError

from gitops_scaffold.analyzer.default import DefaultAnalyzer
from gitops_scaffold.config.settings import ScaffoldSettings
from gitops_scaffold.models.analysis import AnalysisResult
from gitops_scaffold.models.app import ApplicationDefinition
from gitops_scaffold.models.generation import GeneratedFile
from gitops_scaffold.models.generation_report import GenerationReport
from gitops_scaffold.models.report import AnalysisReport
from gitops_scaffold.parsers.base import ParserError
from gitops_scaffold.parsers.registry import detect_parser


def resolve_input(
    source: Path, settings: ScaffoldSettings
) -> tuple[ApplicationDefinition, AnalysisResult]:
    """Resolves ``source`` into ``(application, analysis)`` — the one place
    "no separate generation path" is decided.

    ``.json`` is loaded and trusted as a previously-saved ``AnalysisReport``
    verbatim (no re-analysis — the entire point of the cached-report design).
    Anything else is parsed and analyzed fresh, via the exact same two calls
    ``analyze`` already makes.
    """
    if source.suffix == ".json":
        try:
            report = AnalysisReport.model_validate_json(source.read_text())
        except (OSError, ValidationError) as exc:
            raise ParserError(f"{source}: not a valid analysis report: {exc}") from exc
        return report.application, report.analysis

    parser = detect_parser(source)
    application = parser.parse(source)
    analysis = DefaultAnalyzer(settings).analyze(application)
    return application, analysis


@dataclass(frozen=True)
class OverwriteDecision:
    """The result of comparing this run's about-to-write paths against the
    previous run's managed-file ledger (that run's own ``generation-report.json``,
    if one exists in the output directory).
    """

    #: Exist on disk but weren't recorded as ours by a previous run (or no
    #: previous run exists at all) -- always blocks, ``--force`` or not.
    foreign: tuple[str, ...]
    #: Our own prior output, at a path we're regenerating -- blocks without
    #: ``--force``; overwritten with it.
    managed_conflicts: tuple[str, ...]
    #: Generated by a previous run but not produced by this one (a removed
    #: service, or a layout-shape change) -- blocks without ``--force``;
    #: with it, left in place (never deleted) and recorded/warned about.
    orphaned: tuple[str, ...]

    @property
    def blocked_without_force(self) -> bool:
        return bool(self.foreign or self.managed_conflicts or self.orphaned)


def _load_previous_managed_files(output_dir: Path) -> frozenset[str]:
    report_path = output_dir / "generation-report.json"
    if not report_path.exists():
        return frozenset()
    try:
        report = GenerationReport.model_validate_json(report_path.read_text())
    except (OSError, ValidationError):
        return frozenset()
    return frozenset(report.generated_files)


def plan_overwrite(output_dir: Path, this_run_paths: set[str]) -> OverwriteDecision:
    previous_managed = _load_previous_managed_files(output_dir)
    existing = {path for path in this_run_paths if (output_dir / path).exists()}
    foreign = tuple(sorted(existing - previous_managed))
    managed_conflicts = tuple(sorted(existing & previous_managed))
    orphaned = tuple(sorted(previous_managed - this_run_paths))
    return OverwriteDecision(
        foreign=foreign, managed_conflicts=managed_conflicts, orphaned=orphaned
    )


def write_generated_files(
    output_dir: Path, files: tuple[GeneratedFile, ...], report: GenerationReport
) -> None:
    """Stages every file in a temporary directory first, then copies the
    whole set into ``output_dir`` only once every staged write has
    succeeded — so a failure partway through building the content never
    leaves a partial tree in the real output directory.
    """
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        for file in files:
            staged = tmp_path / file.relative_path
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_text(file.content)
        report_staged = tmp_path / "generation-report.json"
        report_staged.write_text(report.model_dump_json(indent=2) + "\n")

        output_dir.mkdir(parents=True, exist_ok=True)
        for file in files:
            dest = output_dir / file.relative_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(tmp_path / file.relative_path, dest)
        shutil.copy2(report_staged, output_dir / "generation-report.json")
