"""Plain Kubernetes manifest parser (round-tripping existing manifests).

Not yet implemented — a scaffolding placeholder mirroring
:class:`~gitops_scaffold.parsers.compose.ComposeParser`. Intended for
importing an existing Deployment/Service/etc. as a starting
:class:`ApplicationDefinition`, e.g. to re-run analysis on manifests that
weren't originally generated by this tool. See ``docs/roadmap.md``.
"""

from __future__ import annotations

from pathlib import Path

from gitops_scaffold.models.app import ApplicationDefinition
from gitops_scaffold.parsers.base import Parser

_KUBERNETES_KINDS = ("kind: Deployment", "kind: StatefulSet", "kind: DaemonSet")


class KubernetesParser(Parser):
    """Parses existing plain Kubernetes manifests into an :class:`ApplicationDefinition`."""

    format_name = "kubernetes"

    def can_parse(self, path: Path) -> bool:
        if path.suffix not in {".yml", ".yaml"}:
            return False
        try:
            text = path.read_text()
        except OSError:
            return False
        return any(kind in text for kind in _KUBERNETES_KINDS)

    def parse(self, path: Path) -> ApplicationDefinition:
        raise NotImplementedError(
            "Kubernetes manifest parsing is not yet implemented — see docs/roadmap.md."
        )
